### ISSUE TITLE
export() resets foreign key pragma

### ISSUE THREAD

**Issue by karlb** [sql-js/sql.js#233] opened 2018-03-30 09:08 UTC
When calling `export()` on a database, foreign keys are turned off. I would expect `PRAGMA foreign_keys` to return the same value before and after an export. Generally, I would expect export not to change the state of the db at all.

Example from developer console:
```js
> db.run('PRAGMA foreign_keys=ON');
Database {filename: "dbfile_2179398655", db: 5292304, statements: {…}, changeRows: ƒ, changeRow: ƒ, …}

> db.exec('PRAGMA foreign_keys')[0].values[0];
[1]

> db.export()
Uint8Array(32768) [83, 81, 76, 105, 116, 101, 32, 102, 111, 114, 109, 97, 116, 32, 51, 0, 16, 0, 1, 1, 0, 64, 32, 32, 0, 0, 1, 43, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 223, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 43, 0, 46, 28, 176, …]

> db.exec('PRAGMA foreign_keys')[0].values[0];
[0]
```

**Comment by YagoLopez** [comment] 2018-05-21 02:15
I have commented a similar question in other thread. Hope it helps.
https://github.com/kripken/sql.js/issues/221#issuecomment-390499489

**Comment by karlb** [comment] 2018-05-21 16:59
Your comment seems to be about the fact that the export does not contain the pragma information, right? That matches the sqlite behavior and is understandable to me. What I'm surprised about is that doing an export changes the pragma for my existing connection.

**Comment by YagoLopez** [comment] 2018-05-21 21:02
@karlb yes you are right, your case is very strange. I would try to reproduce that behaviour using the online sql gui to assure my code has not errors.

**Comment by seidtgeist** [comment] 2020-05-26 14:58
*[time machine noises]*

This is happening because the export function closes the database file before it’s read into an Uint8Array and then opened again:

https://github.com/sql-js/sql.js/blob/5c40349eff606e4a99b7b184e8b914f32e0026d8/src/api.js#L866-L868

A newly-opened database doesn’t come with prior pragmas.

Could this be documented in the export function, or would it be possible to export the database without closing and re-opening it?

On a related note, I’ve been wondering which pragmas (especially locking_mode and journal_mode) make sense for sql.js since everything is happening in memory buffers anyway?

**Comment by lovasoa** [comment] 2020-05-26 15:10
Yes, we've discussed that in https://github.com/sql-js/sql.js/pull/397
Closing the database and reopening it has many disadvantages. We should be able to just just flush it before exporting, without closing it.

**Comment by lovasoa** [comment] 2020-05-26 15:11
I am going to close this issue as a duplicate of https://github.com/sql-js/sql.js/issues/159
But we should still fix it.

**Closed by lovasoa** 2020-05-26 15:11 UTC

**Comment by seidtgeist** [comment] 2020-05-26 15:53
@lovasoa Makes sense! I’ll read up on those two issues.
