### ISSUE TITLE
How to properly get the generated ID of an inserted row?

### ISSUE THREAD

**Issue by JanisE** [sql-js/sql.js#543] opened 2023-02-09 14:28 UTC
How to properly get the generated ID of an inserted row?
I'm trying it like this, but I get `undefined` as the ID:

```html
<!DOCTYPE html>
<html>
<body>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/sql.js/1.8.0/sql-wasm.js"></script>
  <script>
    initSqlJs({locateFile: () => 'https://cdnjs.cloudflare.com/ajax/libs/sql.js/1.8.0/sql-wasm.wasm'}).then(function(SQL){
      const db = new SQL.Database();
      db.run(`CREATE TABLE texts (
          id INTEGER PRIMARY KEY,
          text VARCHAR NOT NULL
        );`
      );

      const get_last_id = db.prepare('SELECT last_insert_rowid() AS lastid');
      const insert_text = db.prepare('INSERT INTO texts (text) VALUES (:text);');

      for(let i = 0; i < 5; i++){
        insert_text.run({':text': 'text'});
        console.log(get_last_id.getAsObject());
      }
    });
  </script>
</body>
```

**Comment by lovasoa** [comment] 2023-02-09 16:32
Hi ! 
  I'm closing this as a duplicate of https://github.com/sql-js/sql.js/issues/77

  Feel free to comment there

**Closed by lovasoa** 2023-02-09 16:32 UTC
