### ISSUE TITLE
sqlite3_interrupt

### ISSUE THREAD

**Issue by bokolob** [sql-js/sql.js#484] opened 2021-09-27 11:40 UTC
Hello! Is there a way to interrupt long query? I see that sqlite3_interrupt isn't exposed for some reason..

**Comment by lovasoa** [comment] 2021-09-27 12:07
Ill close this as a duplicate of https://github.com/sql-js/sql.js/issues/461

You can comment in that issue if you have more questions.

**Closed by lovasoa** 2021-09-27 12:07 UTC
Labels: duplicate
